### PR TITLE
feat: support for new ICD hosting model

### PR DESCRIPTION
**Pull request by shemau**
### Description

Add support for the IBM Cloud Database new hosting model, including bumping minimum memory requirements from 1G to 4G.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Reference: [Cloud Database Hosting Models](https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-hosting-models)

The [host model switching](https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-hosting-models&interface=api#hosting-models-switching) section has details of the migrations that the service is rolling out. All instances will have to be switched and the [time line](https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-hosting-models&interface=api#hosting-model-transition-timeline) for the migrations is outlined.

During the transition both existing and new models are supported.

Users of this module should consider the changes being implemented by the service. It is recommended that new deployments use the shared or isolated compute models to start, by specifying the host_flavor. It is recommended that existing deployments make updates to control the upgrade process by specifying shared or isolate compute configurations and the resource required to run the service, by adding the host_flavor.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by shemau** [comment]
The only change during upgrade is the group block and results in an update in-place.

This is expected and the exact details vary by the existing deployment.

existing deployment with less then 4G memory: The group memory block will update in-place to 4G of memory.
existing deployment with 4G plus memory: No change.
existing deployment adding host_flavor (as below): The group memory block will update in-place to the flavor chosen.

The upgrade test is safe to skip.

```hcl
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: Terraform used the selected providers to generate the following execution
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: plan. Resource actions are indicated with the following symbols:
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:   ~ update in-place
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:  <= read (data resources)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: Terraform will perform the following actions:
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:   # module.icd_rabbitmq.data.ibm_database_connection.database_connection will be read during apply
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:   # (depends on a resource or a module with changes pending)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:  <= data "ibm_database_connection" "database_connection" {
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + amqps         = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + analytics     = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + bi_connector  = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + cli           = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + deployment_id = "crn:v1:bluemix:public:messages-for-rabbitmq:eu-de:a/abac0df06b644a9cabc6e44f55b3880e:f2d90f99-37e7-4779-a909-411f96edf766::"
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + emp           = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + endpoint_type = "private"
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + grpc          = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + https         = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + id            = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + mongodb       = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + mqtts         = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + mysql         = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + ops_manager   = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + postgres      = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + rediss        = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + secure        = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + stomp_ssl     = (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + user_id       = "admin"
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + user_type     = "database"
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:     }
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:   # module.icd_rabbitmq.ibm_database.rabbitmq_database will be updated in-place
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:   ~ resource "ibm_database" "rabbitmq_database" {
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:         id                        = "crn:v1:bluemix:public:messages-for-rabbitmq:eu-de:a/abac0df06b644a9cabc6e44f55b3880e:f2d90f99-37e7-4779-a909-411f96edf766::"
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:         name                      = "rabbitmq-upg-vqirdq-rabbitmq"
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:         tags                      = []
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:         # (19 unchanged attributes hidden)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       - group {
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:           - group_id = "member" -> null
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:           - cpu {
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:               - allocation_count = 0 -> null
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:             }
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:           - disk {
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:               - allocation_mb = 1024 -> null
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:             }
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:           - members {
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:               - allocation_count = 3 -> null
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:             }
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:           - memory {
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:               - allocation_mb = 1024 -> null
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:             }
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:         }
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:       + group {
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:           + group_id = "member"
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:           + cpu {
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:               + allocation_count = 0
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:             }
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:           + disk {
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:               + allocation_mb = 1024
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:             }
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:           + host_flavor {
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:               + id = "multitenant"
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:             }
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:           + members {
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:               + allocation_count = 3
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:             }
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:           + memory {
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:               + allocation_mb = 4096
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:             }
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:         }
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:         # (3 unchanged blocks hidden)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:     }
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: Plan: 0 to add, 1 to change, 0 to destroy.
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: 
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: Changes to Outputs:
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:   ~ hostname                   = "f2d90f99-37e7-4779-a909-411f96edf766.bpb68u2f0gvaqgd0n64g.private.databases.appdomain.cloud" -> (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185:   ~ port                       = 32495 -> (known after apply)
TestRunCompleteUpgradeExample 2024-06-28T11:18:42Z command.go:185: ╷
```

**Review by iamar7 — COMMENTED** [review]
As per [here](https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-hosting-models&interface=api#hosting-model-transition-timeline) the minimum RAM allocation on multi-tenant instances is 8 GB RAM for RabbitMQ. So shouldn't all the example with `multitenant` member_host_flavor should have 8 GB as default `memory_mb` set.

**Review by iamar7 — APPROVED** [review]
LGTM

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
